services:
  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     
      - "15672:15672"  

  polltest:
    depends_on: 
      - redis 
    build: 
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis